name: Check for CM and Jira issue IDs provided in PR description

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    name: Trigger Reusable Workflow from jira-integration
    uses: jgmeet/jira-integration/.github/workflows/merge-check.yml@main
    secrets: inherit
