name: Checking Change Request & Jira IDs provided in PR description

on:
  pull_request:
    branches:
      - main

jobs:
  call-workflow:
    name: Check for Change Request & Jira IDs provided in PR description
    uses: jgmeet/jira-integration/.github/workflows/merge-check.yml@main
    secrets: inherit
